### ISSUE TITLE
Bug when switching characters + mod compatibility

### ISSUE THREAD

**Issue by mdgrve** [pcrain/GungeonCraft#8] opened 2024-05-16 12:09 UTC
Hi, this is a very cool mod with interesting items but I'm experiencing some issues.

To clarify, I tested this mod with only the dependencies installed and I'm playing on MacOS. Normally, I have a a dozen of other mods installed, some being similar to this one (adding items, NPC's) and they work completely fine.

Issue I'm personally experiencing: 

- After switching characters, the screen goes completely black. Although I can still move and change characters, the only way to fix the black screen is by pressing 'escape' twice to go the pause menu and back. Additionally, a copy of the character I just switched to will still be standing in its original position in the breach. Lastly, the character I chose when entering the breach initially (when starting up the game), will be completely gone from the breach after switching and unable to switch back to. By ending a run (through dying or reaching completion), or using console commands to refresh the breach, all characters will be available to be selected again and this bug can be repeated from the start.

- Additionally, this mod completely stops a similar mod "The Children Of Kaliber" by UnstableStrafe from initializing in any way..

I want to reiterate that this is very well designed mod and the items within all work perfectly. I'm also aware that I'm one of the very few MacOS users that plays (a modded version of) this game, and that some issues just can't be fixed for my case. I also understand that mod compatibility is not always a priority or can even be impossible to address.

Considering the length of this issue I wrote , and the fact that the issues I'm having might be impossible to fix, I would have no problem if you would prefer to delete it from the issue page to keep it clean and bug-free.

Attached is the error log I get when running the game with only this mod and its dependencies installed, as well as an image that clarifies the character switching bug, hopefully it might be of some use to you.

Error log:
<img width="1440" alt="Error log GungeonCraft on MacOS" src="https://github.com/pcrain/GungeonCraft/assets/92294775/2acdf343-03d3-44da-b6f6-21259793fbea">

Character bug clarification:
<img width="1440" alt="Character Bug GungeonCraft on MacOS" src="https://github.com/pcrain/GungeonCraft/assets/92294775/f3606c2c-2612-4a0a-bbfd-78a3fe4b6f7f">

**Comment by pcrain** [comment] 2024-05-16 17:14
@mdgrve Hey, thanks for the bug report and the kind words! :slightly_smiling_face: This is a bizarre issue I was made aware of a month or so ago and have no idea how to track down. The previous report was from somebody on Linux, which is the same OS I develop GungeonCraft on, so it was even more bizarre to me that the issue occurs at all. Now that I know it's an issue on at least 2 systems, that helps narrow some things down, and while I definitely intend to fix this ASAP, I'm unfortunately not able to reproduce it myself nor am I 100% sure what's causing it. Here's what I know / speculate so far:

- The issue is a null reference exception in projectile animation setup code, that happens during initialization, meaning all the setup that happens after it never gets run (so, e.g., half of the mod's guns are missing, among other things).
- GungeonCraft does some extra temporary patching during setup that gets reverted after setup completes, but unfortunately, if anything goes wrong during setup, the temporary patches become permanent, which can mess up any mods loaded after GungeonCraft. This is what results in Children of Kaliber glitching out as well as the black character select screen shenanigans.
- I can (and probably already should've) at least sanity check the setup code so that the temporary patches are reverted even when an error occurs during setup. That won't fix GungeonCraft for you in and of itself, but it'll at least prevent GungeonCraft from dragging every other mod down with it, so I'll get a fix for that up within the next week hopefully. :sweat_smile: 
- I **suspect** (but can't be certain) the issue has to do with some differences in how GPUs load textures that I'm not fully aware of (as I use custom sprite setup code that I don't think other mods use). The only other thing I can think of is that it's some kind of multithreading issue (which I also do a little bit in the setup code), but I already spent some time trying that avenue with the first person that had this problem. I will try to track this down further if I can, but I'm kind of debugging blindly without being able to reproduce it at all. :sweat_smile: 

In the mean time, if you wouldn't mind sending me the full output log from your game the next time this happens, that'd be super helpful! You can find it as follows:

```
How to find LogOutput.log

Automatic (r2modman, Thunderstore Mod Manager):
 1. In your target profile, go to settings.
 2. In settings, press "Browse profile folder"
 3. In the opened folder, go to the folder named "BepInEx"
 4. In there you should find a file named LogOutput.log, that's the file you're looking for.

Manual (no mod manager):
 1. Go to your game's directory.
 2. Go to the folder named BepInEx.
 3. In there you should find a file named LogOutput.log, that's the file you're looking for.
 ```

**Comment by pcrain** [comment] 2024-05-17 01:02
@mdgrve Thanks friend! Yeah the output log doesn't have much in it, but it did confirm my suspicions that this bug is identical to the one I was seeing before.

At your convenience, can you let me know whether the following old versions of GungeonCraft (found on [this page](https://thunderstore.io/c/enter-the-gungeon/p/CaptainPretzel/GungeonCraft/versions/)) work or not? Each of these updates introduced some changes to how sprite loading was handled, and it would help immensely to confirm whether any of these updates have issues:
- version 1.9.0 (I suspect this is the oldest version that will have problems)
- version 1.8.2 (I suspect this is the newest version that will work)
- version 1.5.0
- version 1.4.0

If there are two versions of the same mod in your plugins folder, the newest one will always be loaded, so you'll have to delete and replace each mod dll to test each version. 

If you could try starting each of these versions and sending the output log from each version, I think that'd help more than anything I can do on my end at the moment. Thanks a ton! :smile:

**Comment by mdgrve** [comment] 2024-05-17 14:41
Hey, below I have gathered the output log from each older version you mentioned, together with some points of information I thought would be useful.

- Version 1.9.0 (Crashes my game on startup):
[LogOutput GungeonCraft 1.9.0.log](https://github.com/pcrain/GungeonCraft/files/15350447/LogOutput.GungeonCraft.1.9.0.log)

- Version 1.8.2 (No bugs when switching characters, custom items present in Ammonomicon + compatible with all of my other mods including ChildrenOfKaliber*):
[LogOutput GungeonCraft 1.8.2.log](https://github.com/pcrain/GungeonCraft/files/15350587/LogOutput.GungeonCraft.1.8.2.log)

- Version 1.5.0 (No bugs when switching characters, custom items present in Ammonomicon):
[LogOutput GungeonCraft 1.5.0.log](https://github.com/pcrain/GungeonCraft/files/15350725/LogOutput.GungeonCraft.1.5.0.log)

- Version 1.4.0 (No bugs when switching characters, custom items present in Ammonomicon):
[LogOutput GungeonCraft 1.4.0.log](https://github.com/pcrain/GungeonCraft/files/15351067/LogOutput.GungeonCraft.1.4.0.log)

- Version 1.1.0 (No bugs when switching characters, custom items NOT present in Ammonomicon):
[LogOutput GungeonCraft 1.1.0.log](https://github.com/pcrain/GungeonCraft/files/15351091/LogOutput.GungeonCraft.1.1.0.log)

- Version 1.0.0 (No bugs when switching characters, custom items NOT present in Ammonomicon):
[LogOutput GungeonCraft 1.0.0.log](https://github.com/pcrain/GungeonCraft/files/15351113/LogOutput.GungeonCraft.1.0.0.log)

*For clarification, I dit not check for mod compatibility outside version 1.8.2.

Although I don't think these output logs show significant differences, I hope they can still be of some use to you. Don't hesitate to let me know if there are others ways I could help 👍

**Comment by pcrain** [comment] 2024-05-17 18:39
@mdgrve Thanks a ton for the help, we were able to track the issue down and it turns out it's just a slightly misconfigured manual install. I pinged you on Discord about this as well, but just for posterity for anyone else that encounters this issue: when you download MtGAPI from `Thunderstore`, in addition to copying the main plugin into your plugins folder, you also need to make sure you copy `UnityEngine.CoreModule.MTGAPIPatcher.mm.dll` intto your `.../Enter the Gungeon/BepInEx/monomod/` directory. Then everything should work right. :blush:

**Closed by pcrain** 2024-05-17 18:39 UTC
Labels: bug, help wanted
